//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public Carrera()
        {
            this.Alumno = new HashSet<Alumno>();
        }
    
        public int iCarreraId { get; set; }
        public string sNombre { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
    }
}
